### ISSUE TITLE
Allow passing variables that will be expanded

### ISSUE THREAD

**Issue by boosh** [jaketrent/html-webpack-template#11]
Is there any way to pass variables that will be interpolated in the final output? E.g. I want to use a different prefix to serve my favicons in dev & prod. I'd like to be able to put something like `<link rel="icon" type="image/png" href="$MEDIA_PREFIX/favicons/favicon-32x32.png" sizes="32x32">` in my template and have `$MEDIA_PREFIX` expanded to a value from config.

Is this possible, or could it be added please?

**Comment by bebraw** [comment]
By the looks of it you would have to fork the template to achieve this. Instead of

``` ejs
  <% if (htmlWebpackPlugin.files.favicon) { %>
  <link rel="shortcut icon" href="<%= htmlWebpackPlugin.files.favicon%>">
  <% } %>
```

we would need something far more dynamic. Perhaps there should be support for a mapping like this within the plugin configuration:

``` javascript
{
  ...
  favicons: [
    {
      type: 'image/png',
      href: MEDIA_PREFIX + '/favicons/favicon-32x32.png',
      sizes: '32x32'
    },
    ...
  ]
}
```

Each of those objects would map to a `link rel="icon"`. It's likely possible to pull this off with a bit of EJS.

**Comment by jaketrent** [comment]
@boosh Anything that will work in ejs/underscore template syntax is compatible with the html-webpack-plugin@2.x.  @bebraw is correct above.  You could make this happen, but it'd probably be better in a fork for this specific purpose that you have in mind.

Closing.

**Comment by bebraw** [comment]
Speaking of favicons, there's https://github.com/jantimon/favicons-webpack-plugin now.
