### ISSUE TITLE
Why so much white space?

### ISSUE THREAD

**Issue by Sotorin** [jaketrent/html-webpack-template#40]
Why is there so much white space in resulting HTML?

<img width="747" alt="screen shot 2017-01-06 at 4 22 47 pm" src="https://cloud.githubusercontent.com/assets/1545379/21735069/8c9865aa-d42c-11e6-99c6-63611f7e08cb.png">

**Comment by BrandonBoone** [comment]
This is likely due to all of the optional blocks within [index.ejs](https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs). When options aren't used/skipped you can get some significant whitespace. Also, it looks like all white space in the template is preserved even if the line just contains ejs syntax. It may be interesting to see if the file could be compressed at the end of processing.

**Comment by oomathias** [comment]
You can add this inside your config to remove them:

```js
new HtmlWebpackPlugin({
  minify: {
    collapseWhitespace: true,
    preserveLineBreaks: true,
  },
  ...
})
```

**Comment by jaketrent** [comment]
@oomathias Thanks for the `HtmlWebpackPlugin` option comment.  Closing.
